spring:
  config:
    import: "optional:configserver:"

  application:
    name: api-gateway

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
