server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github-ride:chirag99968/config-repo.git
          clone-on-start: true
          default-label: main
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
